"""Seed data for the PPML/FHE Research Dashboard.

Contains all events, researchers, and resources from the user's catalogue
plus additional venues discovered through research.
"""

from datetime import date
from models import db, Event, Researcher, Resource


def seed_all():
    """Seed the database with all initial data."""
    if Event.query.first():
        return  # Already seeded
    seed_events()
    seed_researchers()
    seed_resources()
    db.session.commit()


def seed_events():
    events = [
        # ========== CONFERENCES (Outside India) ==========
        Event(title="NeurIPS", category="conference",
              website="https://neurips.cc/",
              relevance_tags="ML, DL, PPML, FL, DP",
              location="Outside",
              submission_deadline=date(2026, 5, 22),
              notification_date=date(2026, 9, 22),
              event_start_date=date(2026, 12, 6),
              event_end_date=date(2026, 12, 12),
              description="Top-tier ML conference with strong PPML track. Regularly features FHE, FL, DP papers.",
              status="upcoming"),

        Event(title="ICML - International Conference on Machine Learning", category="conference",
              website="https://icml.cc/",
              relevance_tags="ML, DL, PPML, FL, DP",
              location="Outside",
              submission_deadline=date(2026, 1, 31),
              notification_date=date(2026, 5, 1),
              event_start_date=date(2026, 7, 19),
              event_end_date=date(2026, 7, 25),
              description="Premier ML conference. Strong track for privacy-preserving ML, federated learning.",
              status="upcoming"),

        Event(title="ICLR - International Conference on Learning Representations", category="conference",
              website="https://iclr.cc/",
              relevance_tags="ML, DL, PPML, Representation Learning",
              location="Outside",
              submission_deadline=date(2025, 10, 1),
              notification_date=date(2026, 1, 22),
              event_start_date=date(2026, 4, 24),
              event_end_date=date(2026, 4, 28),
              description="Top ML conference focusing on representation learning. Hosts PML workshop.",
              status="upcoming"),

        Event(title="IEEE SaTML - Conference on Secure and Trustworthy Machine Learning", category="conference",
              edition="3rd",
              website="https://satml.org/",
              association="IEEE",
              relevance_tags="Secure ML, Trustworthy ML, Adversarial ML, PPML",
              location="Outside",
              submission_deadline=date(2025, 10, 2),
              notification_date=date(2025, 12, 10),
              event_start_date=date(2026, 4, 8),
              event_end_date=date(2026, 4, 11),
              description="IEEE conference on secure and trustworthy ML. Covers adversarial ML, privacy, fairness.",
              status="upcoming"),

        Event(title="PEPR - Privacy Engineering Practice and Respect", category="conference",
              website="https://www.usenix.org/conferences/byname/1046",
              association="USENIX",
              relevance_tags="Privacy Engineering, DP, PPML",
              location="Outside",
              description="USENIX conference on privacy engineering practice.",
              status="upcoming"),

        Event(title="CAMLIS - Conference on Applied ML in Information Security", category="conference",
              website="https://www.camlis.org/",
              relevance_tags="Applied ML, Information Security",
              location="Outside",
              description="Conference on applied ML in information security.",
              status="upcoming"),

        Event(title="XAI for Privacy-Preserving Machine Learning", category="conference",
              website="https://xaiworldconference.com/2024/explainable-ai-for-privacy-preserving-machine-learning/",
              relevance_tags="XAI, PPML, Explainability",
              location="Outside",
              description="Track at XAI World Conference on explainable AI for PPML.",
              status="upcoming"),

        Event(title="IACR PPML Workshop", category="workshop",
              website="https://crypto.iacr.org/",
              association="IACR",
              relevance_tags="PPML, FHE, MPC, Cryptography",
              location="Outside",
              description="IACR workshop on privacy-preserving machine learning, co-located with CRYPTO.",
              status="upcoming"),

        Event(title="PST - International Conference on Privacy, Security and Trust", category="conference",
              website="https://pstnet.ca/",
              relevance_tags="Privacy, Security, Trust, PPML",
              location="Outside",
              description="Conference covering privacy, security, and trust in computing.",
              status="upcoming"),

        Event(title="ISC - International Security Conference", category="conference",
              website="https://isc25.skku.edu/",
              relevance_tags="MPC, HE, PKC, PQC",
              location="Outside",
              description="Covers MPC, homomorphic encryption, public-key cryptography, post-quantum crypto.",
              status="upcoming"),

        Event(title="IEEE CSR - Cyber Security and Resilience", category="conference",
              website="https://www.ieee-csr.org/",
              association="IEEE",
              relevance_tags="Cyber Security, Resilience",
              location="Outside",
              city="Chania, Crete, Greece",
              description="IEEE conference on cyber security and resilience.",
              status="upcoming"),

        Event(title="STOC 2026 - Symposium on Theory of Computing", category="conference",
              website="https://acm-stoc.org/stoc2026/",
              association="ACM",
              relevance_tags="Theoretical CS, Cryptography, Complexity",
              location="Outside",
              description="Premier theoretical CS conference. Foundational cryptography and complexity results.",
              status="upcoming"),

        Event(title="HLF - Heidelberg Laureate Forum", category="conference",
              website="https://www.heidelberg-laureate-forum.org/",
              relevance_tags="Laureates, Networking, Mathematics, CS",
              location="Outside",
              description="Forum bringing together laureates and young researchers. Similar to ARCS.",
              status="upcoming"),

        # ========== ADDITIONAL MAJOR CRYPTO/SECURITY CONFERENCES ==========
        Event(title="CRYPTO 2026", category="conference",
              website="https://crypto.iacr.org/",
              association="IACR",
              relevance_tags="Cryptography, FHE, MPC, ZKP",
              location="Outside",
              city="Santa Barbara, CA",
              submission_deadline=date(2026, 2, 13),
              event_start_date=date(2026, 8, 16),
              event_end_date=date(2026, 8, 20),
              description="Flagship IACR cryptography conference. Major venue for FHE, MPC, and ZKP papers.",
              status="upcoming"),

        Event(title="EUROCRYPT 2026", category="conference",
              website="https://eurocrypt.iacr.org/",
              association="IACR",
              relevance_tags="Cryptography, FHE, MPC, PKC",
              location="Outside",
              submission_deadline=date(2025, 10, 2),
              event_start_date=date(2026, 5, 17),
              event_end_date=date(2026, 5, 21),
              description="Major European cryptography conference. Strong FHE and lattice crypto track.",
              status="upcoming"),

        Event(title="ASIACRYPT 2025", category="conference",
              website="https://asiacrypt.iacr.org/",
              association="IACR",
              relevance_tags="Cryptography, FHE, MPC, Lattice",
              location="Outside",
              submission_deadline=date(2025, 5, 14),
              event_start_date=date(2025, 12, 8),
              event_end_date=date(2025, 12, 12),
              description="IACR conference for Asian region. Covers all areas of cryptology.",
              status="upcoming"),

        Event(title="TCC - Theory of Cryptography Conference", category="conference",
              website="https://tcc.iacr.org/",
              association="IACR",
              relevance_tags="Cryptographic Theory, FHE, MPC, Foundations",
              location="Outside",
              description="Theory-focused cryptography conference. Foundational FHE results.",
              status="upcoming"),

        Event(title="PKC - International Conference on Public-Key Cryptography", category="conference",
              website="https://pkc.iacr.org/",
              association="IACR",
              relevance_tags="PKC, FHE, Lattice, PQC",
              location="Outside",
              description="IACR conference on public-key cryptography and applications.",
              status="upcoming"),

        Event(title="ACM CCS - Computer and Communications Security", category="conference",
              website="https://www.sigsac.org/ccs/",
              association="ACM",
              relevance_tags="Security, Privacy, MPC, PPML",
              location="Outside",
              submission_deadline=date(2026, 1, 20),
              event_start_date=date(2026, 11, 15),
              event_end_date=date(2026, 11, 19),
              description="Top ACM security conference. Strong applied crypto and privacy track.",
              status="upcoming"),

        Event(title="USENIX Security 2026", category="conference",
              website="https://www.usenix.org/conference/usenixsecurity26",
              association="USENIX",
              relevance_tags="Security, Privacy, PPML, Systems Security",
              location="Outside",
              submission_deadline=date(2025, 10, 15),
              description="Top systems security conference. PPML, MPC, and FL systems papers.",
              status="upcoming"),

        Event(title="NDSS - Network and Distributed System Security", category="conference",
              website="https://www.ndss-symposium.org/",
              relevance_tags="Network Security, Distributed Systems, FL, PPML",
              location="Outside",
              description="Top network security venue. Distributed learning and privacy papers.",
              status="upcoming"),

        Event(title="PETS / PoPETs - Privacy Enhancing Technologies Symposium", category="conference",
              website="https://petsymposium.org/",
              relevance_tags="PETs, DP, PPML, Anonymity, FHE",
              location="Outside",
              description="Premier venue for privacy-enhancing technologies research. Rolling deadlines.",
              notes="Rolling submission: 4 deadlines per year (typically May 31, Aug 31, Nov 30, Feb 28)",
              status="cfp_open"),

        Event(title="Real World Crypto (RWC) 2026", category="conference",
              website="https://rwc.iacr.org/",
              association="IACR",
              relevance_tags="Applied Cryptography, FHE, MPC, Industry",
              location="Outside",
              event_start_date=date(2026, 3, 25),
              event_end_date=date(2026, 3, 27),
              description="Applied cryptography conference bridging theory and practice. FHE deployment talks.",
              status="upcoming"),

        Event(title="FHE.org Conference 2026", category="conference",
              website="https://fhe.org/",
              relevance_tags="FHE, Homomorphic Encryption, Applications",
              location="Outside",
              description="Annual FHE.org conference dedicated to fully homomorphic encryption.",
              status="upcoming"),

        Event(title="CT-RSA - Cryptographers' Track at RSA", category="conference",
              website="https://ct-rsa.com/",
              relevance_tags="Cryptography, Applied Crypto, FHE",
              location="Outside",
              description="Cryptographers' track at RSA Conference.",
              status="upcoming"),

        Event(title="FC - Financial Cryptography and Data Security", category="conference",
              website="https://fc26.ifca.ai/",
              association="IFCA",
              relevance_tags="Financial Crypto, Privacy, MPC, Blockchain",
              location="Outside",
              description="Conference on financial cryptography and data security.",
              status="upcoming"),

        Event(title="ACSAC - Annual Computer Security Applications Conference", category="conference",
              website="https://www.acsac.org/",
              relevance_tags="Applied Security, PPML, Systems",
              location="Outside",
              description="Applied computer security conference.",
              status="upcoming"),

        Event(title="ESORICS - European Symposium on Research in Computer Security", category="conference",
              website="https://esorics2025.sciencesconf.org/",
              relevance_tags="Security, Privacy, Cryptography, PPML",
              location="Outside",
              description="European computer security research symposium.",
              status="upcoming"),

        Event(title="IEEE EuroS&P - European Symposium on Security and Privacy", category="conference",
              website="https://eurosp2026.ieee-security.org/",
              association="IEEE",
              relevance_tags="Security, Privacy, ML Security",
              location="Outside",
              description="IEEE European security and privacy symposium.",
              status="upcoming"),

        Event(title="ACNS - Applied Cryptography and Network Security", category="conference",
              website="https://acns2026.com/",
              relevance_tags="Applied Cryptography, Network Security, FHE, MPC",
              location="Outside",
              description="Conference on applied cryptography and network security.",
              status="upcoming"),

        Event(title="CODASPY - ACM Conference on Data and Application Security and Privacy", category="conference",
              website="https://www.codaspy.org/",
              association="ACM",
              relevance_tags="Data Security, Privacy, Access Control",
              location="Outside",
              description="ACM conference on data and application security and privacy.",
              status="upcoming"),

        Event(title="MLSys - Conference on ML and Systems", category="conference",
              website="https://mlsys.org/",
              relevance_tags="ML Systems, FL, Distributed ML, Efficiency",
              location="Outside",
              description="Conference on ML systems. Covers FL infrastructure, efficient inference.",
              status="upcoming"),

        # ========== CONFERENCES (India) ==========
        Event(title="CASML - International Conference on Applied AI and Scientific ML", category="conference",
              website="https://iisc.ac.in/events/international-conference-on-applied-ai-and-scientific-machine-learning-casml/",
              relevance_tags="Applied AI, Scientific ML",
              location="India",
              description="IISc conference on applied AI and scientific machine learning.",
              status="upcoming"),

        Event(title="CODS-COMAD", category="conference",
              website="https://cods-comad.in/",
              association="ACM India",
              relevance_tags="Data Science, ML, Data Management",
              location="India",
              description="ACM India conference on data science and data management.",
              status="upcoming"),

        Event(title="INDOCRYPT", category="conference",
              website="https://setsindia.in/indocrypt2024/indocrypt",
              relevance_tags="Cryptography, Indian Crypto Community",
              location="India",
              description="Annual Indian cryptology conference. Part of IACR calendar.",
              status="upcoming"),

        Event(title="SPACE - Security, Privacy, and Applied Cryptography Engineering", category="conference",
              website="https://space2024.cse.iitk.ac.in/",
              relevance_tags="Security, Privacy, Applied Cryptography",
              location="India",
              description="Indian conference on security, privacy, and applied cryptographic engineering.",
              status="upcoming"),

        Event(title="ICMC - International Conference on Mathematics and Computing", category="conference",
              website="https://events.iitbhilai.ac.in/icmc2025/",
              relevance_tags="Mathematics, Computing, Cryptography",
              location="India",
              description="Conference on mathematics and computing at IIT Bhilai.",
              status="upcoming"),

        Event(title="ICCNSML - International Conference on Cryptology and Network Security with ML", category="conference",
              website="https://www.campuzine.com/international-conference-on-cryptology-and-network-security-with-machine-learning-iccnsml/",
              relevance_tags="Cryptology, Network Security, ML",
              location="India",
              description="Conference on cryptology, network security, and machine learning.",
              status="upcoming"),

        Event(title="ICSP 2025 - 4th International Conference on Security & Privacy", category="conference",
              website="https://icsp.co.in/2025/dates.html",
              relevance_tags="Security, Privacy",
              location="India",
              description="Indian conference on security and privacy.",
              status="upcoming"),

        Event(title="MIND-2025 - ML, Image Processing, Network Security and Data Sciences", category="conference",
              website="https://mind2025.mind-society.org/",
              relevance_tags="ML, Image Processing, Network Security, Data Science",
              location="India",
              description="Conference on ML, image processing, network security and data sciences.",
              status="upcoming"),

        Event(title="ANTIC 2025 - Advanced Network Technologies and Intelligent Computing", category="conference",
              website="https://antic.co.in/",
              relevance_tags="Network Technologies, Intelligent Computing",
              location="India",
              description="Conference on advanced network technologies and intelligent computing.",
              status="upcoming"),

        Event(title="ISCS2025 - Intelligent Systems for Cybersecurity", category="conference",
              website="https://iscs2025.ncuindia.edu/",
              relevance_tags="Intelligent Systems, Cybersecurity",
              location="India",
              description="Conference on intelligent systems for cybersecurity.",
              status="upcoming"),

        Event(title="ISEA-ISAP 2026 - International Conference on Security and Privacy", category="conference",
              website="https://isea-isap2026.iitm.ac.in/",
              relevance_tags="Security, Privacy",
              location="India",
              description="IIT Madras conference on security and privacy.",
              status="upcoming"),

        Event(title="XAI-2025", category="conference",
              website="https://xaiworldconference.com/2025/the-conference/",
              relevance_tags="Explainable AI, Security",
              location="India",
              description="XAI World Conference 2025. Explainable AI and security.",
              status="upcoming"),

        Event(title="3rd Symposium on Data for Public Good", category="conference",
              website="https://dataforpublicgood.org.in/symposium-2025/",
              relevance_tags="Data, Public Good, Privacy",
              location="India",
              description="Symposium on data for public good.",
              status="upcoming"),

        Event(title="ICACSDF2025", category="conference",
              relevance_tags="Applied Computing, Security, Digital Forensics",
              location="India",
              description="International Conference on Applied Computing, Security and Digital Forensics.",
              status="upcoming"),

        # ========== JOURNALS ==========
        Event(title="International Journal of Information Security and Privacy (IJISP)", category="journal",
              website="https://dl.acm.org/toc/ijisp-igi/2024/18/1",
              relevance_tags="DP, ML, DL, Information Security",
              description="IGI Global journal on information security and privacy.",
              status="ongoing"),

        Event(title="Security and Privacy (Wiley)", category="journal",
              website="https://onlinelibrary.wiley.com/journal/24756725",
              relevance_tags="Security Protocols, Healthcare Security, Cryptography, Biometrics",
              description="Wiley journal covering security protocols across sectors including healthcare, business, society.",
              status="ongoing"),

        Event(title="IEEE Security and Privacy", category="journal",
              website="https://www.computer.org/csdl/magazine/sp",
              association="IEEE",
              relevance_tags="Responsible AI, DL, Security, Privacy",
              description="IEEE magazine on security and privacy.",
              status="ongoing"),

        Event(title="ACM Transactions on Privacy and Security (TOPS)", category="journal",
              website="https://dl.acm.org/journal/TOPS",
              association="ACM",
              relevance_tags="Security Technologies, Privacy Policies, Secure Systems",
              description="ACM journal on privacy and security. Covers security fundamentals, secure systems, privacy applications.",
              status="ongoing"),

        Event(title="Foundations and Trends in ML", category="journal",
              website="https://www.nowpublishers.com/mal",
              relevance_tags="Ethical AI, Automated DL, ML Foundations",
              description="Survey and tutorial journal for ML. Ethical AI, automated deep learning.",
              status="ongoing"),

        Event(title="Machine Learning and Knowledge Extraction (MAKE)", category="journal",
              website="https://www.mdpi.com/journal/make/about",
              relevance_tags="ML, Knowledge Extraction, Privacy, NLP, Neural Networks",
              description="MDPI journal on ML, knowledge representation, privacy, transfer learning.",
              status="ongoing"),

        Event(title="Machine Learning: Science and Technology", category="journal",
              website="https://publishingsupport.iopscience.iop.org/journals/machine-learning-science-and-technology/",
              relevance_tags="Interdisciplinary ML, Physics, Neural Networks, Bayesian Methods",
              description="IOP journal on interdisciplinary ML. Neural architectures, kernel methods, probabilistic methods.",
              status="ongoing"),

        Event(title="Journal of Privacy and Confidentiality", category="journal",
              website="https://journalprivacyconfidentiality.org/index.php/jpc/index",
              relevance_tags="DP, Privacy, Confidentiality, Multi-disciplinary",
              description="Open-access journal on DP for privacy-preserving scenarios. Multi-disciplinary.",
              status="ongoing"),

        Event(title="Journal of Machine Learning Research (JMLR)", category="journal",
              website="https://www.jmlr.org/papers/",
              relevance_tags="ML, Open Access",
              description="Premier open-access ML journal.",
              status="ongoing"),

        Event(title="Proceedings on Privacy Enhancing Technologies (PoPETs)", category="journal",
              website="https://petsymposium.org/",
              relevance_tags="PETs, Privacy, DP, FHE, MPC, Anonymity",
              description="Gold open-access journal for PETs research. Rolling submission deadlines.",
              notes="Rolling submission: 4 issues per year",
              status="ongoing"),

        Event(title="IEEE TPAMI - Pattern Analysis and Machine Intelligence", category="journal",
              website="https://ieeexplore.ieee.org/xpl/topAccessedArticles.jsp?punumber=34",
              association="IEEE",
              relevance_tags="ML, Computer Vision, Pattern Analysis",
              description="Top IEEE journal on ML and computer vision.",
              status="ongoing"),

        Event(title="AI Review (Springer)", category="journal",
              website="https://link.springer.com/journal/10462",
              relevance_tags="AI, ML, Reviews",
              description="Springer journal publishing AI reviews and surveys.",
              status="ongoing"),

        Event(title="Journal of Cryptology", category="journal",
              website="https://www.springer.com/journal/145",
              association="IACR / Springer",
              relevance_tags="Cryptography, FHE, MPC, Foundations",
              description="IACR journal. Premier venue for foundational cryptography including FHE.",
              status="ongoing"),

        Event(title="IEEE TDSC - Transactions on Dependable and Secure Computing", category="journal",
              website="https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8858",
              association="IEEE",
              relevance_tags="Secure Computing, Dependability, Privacy",
              description="IEEE journal on dependable and secure computing.",
              status="ongoing"),

        Event(title="IEEE TIFS - Transactions on Information Forensics and Security", category="journal",
              website="https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=10206",
              association="IEEE",
              relevance_tags="Information Forensics, Security, Privacy, Biometrics",
              description="IEEE journal on information forensics and security.",
              status="ongoing"),

        Event(title="Security and Privacy in AI: Human Interaction, Awareness and Protection", category="journal",
              website="https://www.mdpi.com/journal/applsci/special_issues/43JJT8KEI8",
              relevance_tags="AI Security, Privacy, Human Interaction",
              description="MDPI Applied Sciences special issue on security and privacy in AI.",
              status="cfp_open"),

        # ========== WORKSHOPS ==========
        Event(title="AISEC 2024 - ACM Workshop on AI Security", category="workshop",
              website="https://aisec.cc/",
              association="ACM",
              relevance_tags="AI Security, Adversarial ML, PPML",
              location="Outside",
              description="ACM workshop on artificial intelligence and security.",
              status="upcoming"),

        Event(title="PML - Private ML Workshop @ ICLR", category="workshop",
              website="https://pml-workshop.github.io/iclr24/",
              relevance_tags="Private ML, FL, DP, FHE, MPC",
              location="Outside",
              description="Workshop on private machine learning at ICLR.",
              status="upcoming"),

        Event(title="PPAI - Privacy-Preserving AI @ AAAI", category="workshop",
              website="https://aaai-ppai24.github.io/",
              relevance_tags="PPML, DP, FL, FHE",
              location="Outside",
              description="AAAI workshop on privacy-preserving artificial intelligence.",
              status="upcoming"),

        Event(title="DLSP - Deep Learning and Security Workshop", category="workshop",
              website="https://dlsp2024.ieee-security.org/",
              association="IEEE",
              relevance_tags="DL, Security, Adversarial ML",
              location="Outside",
              description="IEEE workshop on deep learning and security.",
              status="upcoming"),

        Event(title="IEEE S&P 2025 - Symposium on Security and Privacy", category="workshop",
              website="https://sp2025.ieee-security.org/",
              association="IEEE",
              relevance_tags="Security, Privacy, PPML, MPC, FHE",
              location="Outside",
              description="IEEE Symposium on Security and Privacy (Oakland).",
              status="upcoming"),

        Event(title="DSML 2024 - Dependable and Secure ML", category="workshop",
              website="https://dependablesecureml.github.io/",
              relevance_tags="Dependable ML, Secure ML",
              location="Outside",
              description="Workshop on dependable and secure machine learning.",
              status="upcoming"),

        Event(title="AISCC - NDSS Workshop on AI Systems with Confidential Computing", category="workshop",
              website="https://sites.google.com/view/aiscc2024",
              relevance_tags="AI, Confidential Computing, TEE, FHE",
              location="Outside",
              description="NDSS workshop on AI systems with confidential computing.",
              status="upcoming"),

        Event(title="CSCML - Intl Symposium on Cyber Security, Cryptology and ML", category="workshop",
              website="https://www.cscml.org/",
              relevance_tags="Cyber Security, Cryptology, ML",
              location="Outside",
              description="Symposium on cyber security, cryptology, and machine learning.",
              status="upcoming"),

        Event(title="RWMPC 2025 - Real World MPC Workshop", category="workshop",
              website="https://www.mpcalliance.org/rwmpc-2025",
              association="MPC Alliance",
              relevance_tags="MPC, Secure Computation, Privacy",
              location="Outside",
              description="Real World MPC workshop by MPC Alliance.",
              status="upcoming"),

        Event(title="LightSEC 2025 - Lightweight Cryptography for Security & Privacy", category="workshop",
              website="https://www.encrypt-on.com/activities/conferences/lightsec-2025/",
              relevance_tags="Lightweight Cryptography, IoT Security, Privacy",
              location="Outside",
              city="Istanbul, Turkey",
              description="Workshop on lightweight cryptography for security and privacy.",
              status="upcoming"),

        Event(title="AAMAD 2025 - Advancing AI and ML Across Disciplines", category="workshop",
              website="https://antic.co.in/workshop.html",
              relevance_tags="AI, ML, Cross-disciplinary",
              location="India",
              description="Workshop on advancing AI and ML across disciplines.",
              status="upcoming"),

        Event(title="TPDP 2025 - Theory and Practice of Differential Privacy", category="workshop",
              website="https://tpdp.journalprivacyconfidentiality.org/",
              relevance_tags="DP, Privacy, Theory and Practice",
              location="Outside",
              description="Workshop on the theory and practice of differential privacy.",
              status="upcoming"),

        Event(title="WAHC - Workshop on Encrypted Computing & Applied HE", category="workshop",
              website="https://homomorphicencryption.org/workshops/",
              relevance_tags="FHE, HE, Encrypted Computing, Applications",
              location="Outside",
              description="Workshop on encrypted computing and applied homomorphic encryption. Co-located with ACM CCS.",
              status="upcoming"),

        Event(title="FL@NeurIPS - Federated Learning Workshop", category="workshop",
              website="https://federated-learning.org/",
              relevance_tags="FL, Federated Learning, Privacy",
              location="Outside",
              description="Federated learning workshop at NeurIPS.",
              status="upcoming"),

        Event(title="WPES - Workshop on Privacy in the Electronic Society", category="workshop",
              website="https://wpes.tech/",
              association="ACM",
              relevance_tags="Privacy, Electronic Society, DP",
              location="Outside",
              description="ACM workshop on privacy in the electronic society. Co-located with CCS.",
              status="upcoming"),

        # ========== SUMMER/WINTER SCHOOLS ==========
        Event(title="BIU Winter School on Cryptography", category="school",
              website="https://cyber.biu.ac.il/",
              relevance_tags="Cryptography, FHE, MPC, Foundations",
              location="Outside",
              city="Bar-Ilan University, Israel",
              description="Annual winter school on cryptography at Bar-Ilan University. Covers FHE, MPC, and more.",
              status="upcoming"),

        Event(title="IACR School on Cryptography", category="school",
              website="https://iacr.org/schools/",
              association="IACR",
              relevance_tags="Cryptography, FHE, MPC",
              location="Outside",
              description="IACR-sponsored schools on various cryptographic topics.",
              status="upcoming"),

        Event(title="HE Standardization Workshops", category="school",
              website="https://homomorphicencryption.org/",
              relevance_tags="FHE, Standardization, HE",
              location="Outside",
              description="HomomorphicEncryption.org standardization meetings and workshops.",
              status="upcoming"),

        # ========== SEMINARS ==========
        Event(title="PriSec-ML - Privacy and Security in ML Seminars", category="seminar",
              website="https://prisec-ml.github.io/",
              relevance_tags="Privacy, Security, ML, Seminar Series",
              description="Regular seminar series on privacy and security in ML.",
              status="ongoing"),

        Event(title="SPML Seminar - Security and Privacy in ML", category="seminar",
              website="https://vsehwag.github.io/SPML_seminar/",
              relevance_tags="Security, Privacy, ML, Seminar Series",
              description="Seminar series on ML security and privacy.",
              status="ongoing"),

        # ========== CALL FOR CHAPTERS ==========
        Event(title="Privacy Salon - Call for Chapters", category="call_for_chapters",
              website="https://www.privacysalon.org/",
              relevance_tags="Privacy, Book Chapter",
              description="Privacy Salon call for book chapters.",
              status="cfp_open"),

        Event(title="Managing Sensitive Health Data Through FL and Generative AI", category="call_for_chapters",
              website="https://www.igi-global.com/publish/call-for-papers/call-details/9323",
              relevance_tags="FL, Generative AI, Health Data, Privacy",
              description="IGI Global call for chapters: privacy-preserving techniques for health data using FL and GenAI.",
              status="cfp_open"),

        Event(title="AI and Security - Call for Book Chapters", category="call_for_chapters",
              website="https://dmatheorynet.blogspot.com/2025/08/dmanet-call-for-book-chapters.html",
              relevance_tags="AI, Security, Book Chapter",
              description="Call for book chapters on artificial intelligence and security.",
              status="cfp_open"),

        Event(title="PPAI in Digital Healthcare (SAGE)", category="call_for_chapters",
              website="https://journals.sagepub.com/page/dhj/collections/call-for-papers/privacy-preserving-artificial-intelligence-in-digital-healthcare",
              relevance_tags="PPAI, Healthcare, Privacy, DP",
              description="SAGE Digital Health Journal call for papers on privacy-preserving AI in digital healthcare.",
              status="cfp_open"),
    ]
    db.session.add_all(events)


def seed_researchers():
    researchers = [
        Researcher(name="Andrew Trask",
                   website="https://scholar.google.com/citations?hl=en&user=2Ajxf1sAAAAJ",
                   affiliation="OpenMined (Founder)",
                   research_areas="Federated Learning, PySyft, Privacy-Preserving ML"),

        Researcher(name="Aurélien Bellet",
                   website="http://researchers.lille.inria.fr/abellet/teaching/private_machine_learning_course.html",
                   affiliation="Inria (ML Researcher)",
                   research_areas="Private ML, Federated Learning, DP",
                   notes="Has a GitHub-based PPML course"),

        Researcher(name="Vinod Vaikunthanathan",
                   website="https://people.csail.mit.edu/vinodv/",
                   affiliation="MIT CSAIL / Duality Technologies (Co-founder)",
                   research_areas="FHE, Lattice Cryptography, Foundations"),

        Researcher(name="Nalini Ratha",
                   website="https://nalini-ratha.github.io/",
                   affiliation="SUNY (Empire State Professor)",
                   research_areas="FHE Applications, Computer Vision, Biometrics, CVPR"),

        Researcher(name="Staal A. Vinterbo",
                   website="https://staal.folk.ntnu.no/",
                   affiliation="NTNU (Department of Information Security and Communication Technology)",
                   research_areas="Differential Privacy"),

        Researcher(name="Jeongeun Park",
                   website="https://sites.google.com/view/jeongeunpark/home",
                   affiliation="NTNU (Associate Professor, Information Security)",
                   research_areas="Cryptography, Privacy"),

        Researcher(name="Arpita Patra",
                   website="https://www.csa.iisc.ac.in/~arpita/",
                   affiliation="IISc Bangalore (Associate Professor, CSA)",
                   research_areas="Secure MPC, PPML"),

        Researcher(name="Saikrishna Badrinarayanan",
                   website="https://scholar.google.com/citations?user=GCfsAJIAAAAJ&hl=en",
                   affiliation="LinkedIn (Cryptography and Privacy)",
                   research_areas="Cryptography, Security, Privacy"),

        Researcher(name="J. Harshan",
                   website="https://scholar.google.com/citations?user=kv_Ko5sAAAAJ&hl=en",
                   affiliation="IIT Delhi",
                   research_areas="Homomorphic Encryption, Federated Learning"),

        Researcher(name="Ranjitha Prasad",
                   website="https://scholar.google.com/citations?user=ADJe1AsAAAAJ&hl=en",
                   affiliation="IIT Delhi",
                   research_areas="Federated Learning"),

        Researcher(name="B. N. Bharath",
                   website="https://scholar.google.com/citations?user=AOuGtukAAAAJ&hl=en",
                   affiliation="IIT Dharwad",
                   research_areas="Federated Learning, Machine Learning"),

        Researcher(name="Will Abramson",
                   website="https://drwip.com/",
                   affiliation="Independent Researcher",
                   research_areas="Privacy, Decentralized Identity"),

        # Additional key researchers in FHE/PPML
        Researcher(name="Craig Gentry",
                   website="https://crypto.stanford.edu/craig/",
                   affiliation="TripleBlind / formerly IBM Research",
                   research_areas="FHE (inventor of first FHE scheme), Lattice Cryptography",
                   notes="Invented the first fully homomorphic encryption scheme in 2009"),

        Researcher(name="Zvika Brakerski",
                   website="https://www.weizmann.ac.il/math/brakerski/",
                   affiliation="Weizmann Institute of Science",
                   research_areas="FHE, Lattice Cryptography, BGV Scheme"),

        Researcher(name="Kristin Lauter",
                   website="https://www.kristinlauter.com/",
                   affiliation="Meta AI (Director of Research)",
                   research_areas="FHE, PPML, Cryptography for ML",
                   notes="Pioneer in FHE for ML applications"),

        Researcher(name="Nigel Smart",
                   website="https://homes.esat.kuleuven.be/~nsmart/",
                   affiliation="KU Leuven / Zama",
                   research_areas="FHE, MPC, IACR, Applied Cryptography",
                   notes="Former IACR President. Co-founder of FHE/MPC companies."),

        Researcher(name="Shai Halevi",
                   website="https://shaih.github.io/",
                   affiliation="Algorand Foundation / formerly IBM",
                   research_areas="FHE, HElib, Cryptography",
                   notes="Co-developer of HElib, BGV scheme"),

        Researcher(name="Kim Laine",
                   website="https://scholar.google.com/citations?user=MGXK0OoAAAAJ",
                   affiliation="Microsoft Research",
                   research_areas="FHE, Microsoft SEAL, PPML"),

        Researcher(name="Jung Hee Cheon",
                   website="https://www.math.snu.ac.kr/~jhcheon/",
                   affiliation="Seoul National University / CryptoLab",
                   research_areas="FHE, CKKS Scheme, HEAAN",
                   notes="Co-inventor of CKKS/HEAAN approximate HE scheme"),

        Researcher(name="Yongsoo Song",
                   website="https://yongsoosong.github.io/",
                   affiliation="Seoul National University",
                   research_areas="FHE, CKKS, Efficient HE"),

        Researcher(name="Cynthia Dwork",
                   website="https://seas.harvard.edu/person/cynthia-dwork",
                   affiliation="Harvard University",
                   research_areas="Differential Privacy (inventor), Fairness, Foundations",
                   notes="Invented differential privacy"),

        Researcher(name="Ilya Mironov",
                   website="https://scholar.google.com/citations?user=BXBdFCoAAAAJ",
                   affiliation="Apple (ML Privacy)",
                   research_areas="Differential Privacy, Rényi DP, PPML"),

        Researcher(name="Ran Canetti",
                   website="https://www.cs.bu.edu/fac/canetti/",
                   affiliation="Boston University",
                   research_areas="MPC, Universal Composability, Cryptographic Foundations"),

        Researcher(name="Yehuda Lindell",
                   website="https://u.cs.biu.ac.il/~lindell/",
                   affiliation="Bar-Ilan University / Coinbase",
                   research_areas="MPC, Secure Computation, Practical MPC"),

        Researcher(name="Benny Pinkas",
                   website="https://www.pinkas.net/",
                   affiliation="Bar-Ilan University / Aptos Labs",
                   research_areas="PSI, MPC, Secure Computation"),

        Researcher(name="Brendan McMahan",
                   website="https://scholar.google.com/citations?user=iKPWydkAAAAJ",
                   affiliation="Google (Research Scientist)",
                   research_areas="Federated Learning (inventor of FedAvg), PPML",
                   notes="Originated the federated learning framework at Google"),

        Researcher(name="Peter Kairouz",
                   website="https://kairouzp.github.io/",
                   affiliation="Google Research",
                   research_areas="Federated Learning, Differential Privacy, PPML"),

        Researcher(name="Ilya Razenshteyn",
                   website="https://scholar.google.com/citations?user=cu-nR8gAAAAJ",
                   affiliation="CipherMode Labs",
                   research_areas="FHE, Approximate Nearest Neighbors, PPML"),
    ]
    db.session.add_all(researchers)


def seed_resources():
    resources = [
        # ========== LIBRARIES ==========
        Resource(name="OpenFHE", resource_type="library",
                 website="https://www.openfhe.org/",
                 description="Open-source FHE library supporting BGV, BFV, CKKS, FHEW, TFHE schemes.",
                 tags="FHE, C++, Open Source"),

        Resource(name="Microsoft SEAL", resource_type="library",
                 website="https://github.com/microsoft/SEAL",
                 description="Microsoft's homomorphic encryption library. Supports BFV and CKKS schemes.",
                 tags="FHE, C++, Microsoft, BFV, CKKS"),

        Resource(name="TenSEAL", resource_type="library",
                 website="https://github.com/OpenMined/TenSEAL",
                 description="Library for doing HE operations on tensors. Built on Microsoft SEAL. Python-friendly.",
                 tags="FHE, Python, Tensors, OpenMined"),

        Resource(name="ConcreteML", resource_type="library",
                 website="https://docs.zama.ai/concrete-ml",
                 description="Zama's ML framework for FHE. Run ML models on encrypted data.",
                 tags="FHE, ML, Python, Zama"),

        Resource(name="HEAAN", resource_type="library",
                 website="https://github.com/snucrypto/HEAAN",
                 description="Homomorphic Encryption for Arithmetic of Approximate Numbers (CKKS scheme).",
                 tags="FHE, CKKS, Approximate HE"),

        Resource(name="PySyft", resource_type="library",
                 website="https://github.com/OpenMined/PySyft",
                 description="OpenMined's library for secure and private deep learning. FL, DP, MPC support.",
                 tags="FL, DP, MPC, Python, OpenMined"),

        Resource(name="TensorFlow Federated", resource_type="library",
                 website="https://www.tensorflow.org/federated",
                 description="Google's open-source framework for federated learning on decentralized data.",
                 tags="FL, TensorFlow, Google"),

        Resource(name="Flower", resource_type="library",
                 website="https://flower.ai/",
                 description="Unified framework for federated learning. Framework-agnostic.",
                 tags="FL, Framework-Agnostic, Python"),

        Resource(name="NVIDIA FLARE", resource_type="library",
                 website="https://developer.nvidia.com/flare",
                 description="NVIDIA SDK for FL with extensions for DP, HE, and secure aggregation.",
                 tags="FL, DP, HE, NVIDIA, GPU"),

        Resource(name="DP Auditorium", resource_type="library",
                 website="https://developers.googleblog.com/en/sharing-our-latest-differential-privacy-milestones-and-advancements/",
                 description="Google's differential privacy tools and auditing library.",
                 tags="DP, Google, Auditing"),

        Resource(name="PyTorch", resource_type="library",
                 website="https://pytorch.org/",
                 description="Deep learning framework by Meta. Foundation for many PPML tools.",
                 tags="DL, ML, Python, Meta"),

        Resource(name="TensorFlow", resource_type="library",
                 website="https://www.tensorflow.org/",
                 description="Google's ML framework. Foundation for TensorFlow Federated and TF Privacy.",
                 tags="DL, ML, Python, Google"),

        Resource(name="Opacus", resource_type="library",
                 website="https://opacus.ai/",
                 description="Meta's library for training PyTorch models with differential privacy.",
                 tags="DP, PyTorch, Meta"),

        Resource(name="Google DP Library", resource_type="library",
                 website="https://github.com/google/differential-privacy",
                 description="Google's differential privacy library with multiple language bindings.",
                 tags="DP, Google, C++, Java, Go"),

        Resource(name="TFHE-rs", resource_type="library",
                 website="https://github.com/zama-ai/tfhe-rs",
                 description="Zama's pure Rust implementation of TFHE for boolean and integer FHE.",
                 tags="FHE, TFHE, Rust, Zama"),

        Resource(name="Lattigo", resource_type="library",
                 website="https://github.com/tuneinsight/lattigo",
                 description="Go library for lattice-based multiparty homomorphic encryption.",
                 tags="FHE, Go, Lattice, Multiparty"),

        Resource(name="HElib", resource_type="library",
                 website="https://github.com/homenc/HElib",
                 description="Early open-source FHE library by Shai Halevi and Victor Shoup. BGV scheme.",
                 tags="FHE, BGV, C++"),

        # ========== COMPANIES ==========
        Resource(name="Duality Technologies", resource_type="company",
                 website="https://dualitytech.com/",
                 description="Operationalizes Privacy Enhancing Technologies (PETs). FHE-based data collaboration.",
                 tags="FHE, PETs, Enterprise"),

        Resource(name="Zama", resource_type="company",
                 website="https://www.zama.ai/",
                 description="Open-source FHE tooling company. Builds Concrete, TFHE-rs, ConcreteML.",
                 tags="FHE, Open Source, ML"),

        Resource(name="Apheris", resource_type="company",
                 website="https://www.apheris.com/",
                 description="Federated data infrastructure for privacy-preserving analytics.",
                 tags="FL, Privacy, Enterprise"),

        Resource(name="Opaque Systems", resource_type="company",
                 website="https://opaque.co/",
                 description="Confidential computing platform for analytics on encrypted data.",
                 tags="Confidential Computing, Analytics, TEE"),

        Resource(name="Arcium", resource_type="company",
                 website="https://www.arcium.com/",
                 description="Privacy infrastructure using MPC and FHE.",
                 tags="MPC, FHE, Blockchain"),

        Resource(name="Roseman Labs", resource_type="company",
                 website="https://rosemanlabs.com/en/",
                 description="MPC-based secure computation platform.",
                 tags="MPC, Secure Computation, Enterprise"),

        Resource(name="Sherpa.ai", resource_type="company",
                 website="https://sherpa.ai/",
                 description="Privacy-preserving federated learning platform.",
                 tags="FL, Privacy, Enterprise"),

        Resource(name="Technology Innovation Institute (TII)", resource_type="company",
                 website="https://tii.ae/",
                 description="UAE-based research institute with cryptography and AI research groups.",
                 tags="Research, Cryptography, AI"),

        Resource(name="CryptoLab", resource_type="company",
                 website="https://www.cryptolab.co.kr/",
                 description="Company behind HEAAN/CKKS scheme. FHE solutions.",
                 tags="FHE, CKKS, HEAAN"),

        Resource(name="Inpher", resource_type="company",
                 website="https://inpher.io/",
                 description="Secret computing platform using MPC and FHE.",
                 tags="MPC, FHE, Secret Computing"),

        # ========== PLATFORMS ==========
        Resource(name="FedML", resource_type="platform",
                 website="https://fedml.ai/",
                 description="Open platform for federated learning and distributed training.",
                 tags="FL, Distributed ML, Platform"),

        Resource(name="PrivacyML MIT CSAIL", resource_type="platform",
                 website="https://www.csail.mit.edu/research/privacyml-privacy-preserving-framework-machine-learning",
                 description="MIT CSAIL privacy-preserving framework for ML.",
                 tags="PPML, MIT, Research"),

        Resource(name="Microsoft PPML Innovation", resource_type="platform",
                 website="https://www.microsoft.com/en-us/research/group/privacy-preserving-machine-learning-innovation/",
                 description="Microsoft Research group on privacy-preserving ML innovation.",
                 tags="PPML, Microsoft Research"),

        Resource(name="Class Central PPML", resource_type="platform",
                 website="https://www.classcentral.com/subject/privacy-preserving-machine-learning",
                 description="Course aggregator for PPML courses and MOOCs.",
                 tags="Courses, PPML, Learning"),

        Resource(name="NIST for PPML", resource_type="platform",
                 website="https://www.nist.gov/blogs/cybersecurity-insights/uk-us-blog-series-privacy-preserving-federated-learning-introduction",
                 description="NIST resources on privacy-preserving federated learning.",
                 tags="NIST, FL, Standards"),

        Resource(name="Sony AI Privacy", resource_type="platform",
                 website="https://ai.sony/projects/imaging_and_sensing/privacy-and-data-protection/",
                 description="Sony AI privacy and data protection research projects.",
                 tags="Privacy, Sony, Industry Research"),

        Resource(name="Guardora", resource_type="platform",
                 website="https://guardora.ai/",
                 description="Platform for FHE, vertical/horizontal FL, and transfer learning.",
                 tags="FHE, FL, Transfer Learning"),

        Resource(name="FlexOlmo", resource_type="platform",
                 website="https://allenai.org/blog/flexolmo",
                 description="Allen AI flexible language model platform.",
                 tags="LLM, AI2"),

        Resource(name="Cryptology ePrint Archive", resource_type="platform",
                 website="https://eprint.iacr.org/",
                 description="IACR preprint server for cryptology research. Essential for FHE papers.",
                 tags="Preprints, Cryptography, FHE, IACR"),

        # ========== CODE REPOS ==========
        Resource(name="Papers With Code - Privacy Preserving", resource_type="code_repo",
                 website="https://paperswithcode.com/task/privacy-preserving",
                 description="Papers with code for privacy-preserving ML tasks.",
                 tags="Papers, Code, PPML"),

        Resource(name="Papers With Code - Privacy Preserving Deep Learning", resource_type="code_repo",
                 website="https://paperswithcode.com/task/privacy-preserving-deep-learning",
                 description="Papers with code specifically for privacy-preserving deep learning.",
                 tags="Papers, Code, PPDL"),

        Resource(name="Packt PPML", resource_type="code_repo",
                 website="https://github.com/PacktPublishing/Privacy-Preserving-Machine-Learning",
                 description="Code repository for Packt's PPML book.",
                 tags="Book, Code, PPML"),

        # ========== FRAMEWORKS ==========
        Resource(name="CryptoNets", resource_type="framework",
                 website="https://github.com/microsoft/CryptoNets",
                 description="Microsoft Research: evaluating neural networks on encrypted data using levelled HE.",
                 tags="FHE, Neural Networks, Microsoft Research"),

        Resource(name="Gazelle", resource_type="framework",
                 website="https://dl.acm.org/doi/10.5555/3277203.3277326",
                 description="Combines HE with 2PC (garbled circuits) for efficient private inference.",
                 tags="FHE, 2PC, Garbled Circuits, Private Inference"),

        Resource(name="CrypTFlow", resource_type="framework",
                 website="https://www.microsoft.com/en-us/research/publication/cryptflow-secure-tensorflow-inference/",
                 description="Microsoft Research: secure TensorFlow inference via 2PC for DNN.",
                 tags="2PC, DNN, TensorFlow, Microsoft Research"),

        Resource(name="ENCRYPT", resource_type="framework",
                 website="https://encrypt-project.eu/",
                 description="Scalable privacy-preserving framework (EU project).",
                 tags="PPML, Scalable, EU"),

        Resource(name="MP-SPDZ", resource_type="framework",
                 website="https://github.com/data61/MP-SPDZ",
                 description="Versatile framework for multi-party computation. Supports many MPC protocols.",
                 tags="MPC, Protocols, Benchmarking"),

        Resource(name="ABY/ABY3", resource_type="framework",
                 website="https://github.com/encryptogroup/ABY",
                 description="Framework for efficient mixed-protocol secure two-party/three-party computation.",
                 tags="MPC, 2PC, 3PC, Mixed Protocol"),

        # ========== ORGANISATIONS ==========
        Resource(name="FHE.org", resource_type="organisation",
                 website="https://fhe.org/",
                 description="Community dedicated to fully homomorphic encryption. Runs conferences, meetups, resources.",
                 tags="FHE, Community, Conferences"),

        Resource(name="ACL SIGSEC", resource_type="organisation",
                 website="https://sig.llmsecurity.net/",
                 description="ACL Special Interest Group on Security. LLM security focus.",
                 tags="NLP, Security, LLM"),

        Resource(name="RISE Sweden - PPML", resource_type="organisation",
                 website="https://www.ri.se/en/what-we-do/expertises/privacy-preserving-machine-learning",
                 description="RISE Research Institutes of Sweden - PPML expertise group.",
                 tags="PPML, Sweden, Research Institute"),

        Resource(name="ML Collective", resource_type="organisation",
                 website="https://mlcollective.org/events/",
                 description="Non-profit organization for collaborative ML research and events.",
                 tags="ML, Community, Events"),

        Resource(name="HomomorphicEncryption.org", resource_type="organisation",
                 website="https://homomorphicencryption.org/",
                 description="Industry consortium for HE standardization. Runs WAHC workshop.",
                 tags="FHE, Standardization, Industry"),

        Resource(name="MPC Alliance", resource_type="organisation",
                 website="https://www.mpcalliance.org/",
                 description="Industry alliance for multi-party computation. Runs RWMPC workshop.",
                 tags="MPC, Industry, Alliance"),

        Resource(name="OpenMined", resource_type="organisation",
                 website="https://openmined.org/",
                 description="Open-source community for privacy-preserving AI. Builds PySyft, TenSEAL.",
                 tags="PPML, Open Source, FL, DP"),

        Resource(name="PPML Research Group - University of Washington", resource_type="organisation",
                 website="https://faculty.washington.edu/mdecock/ppml/",
                 description="University of Washington PPML research group.",
                 tags="PPML, Research, Academic"),
    ]
    db.session.add_all(resources)
